# Generated by Django 4.2.3 on 2023-07-31 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='principal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=50)),
                ('campania', models.CharField(max_length=200)),
                ('recaudos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_donativos', models.IntegerField()),
            ],
            options={
                'db_table': 'categorias_campanias',
            },
        ),
    ]
