# Generated by Django 4.2.3 on 2023-07-31 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donacion', '0002_principal_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='principal',
            name='recaudos',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='principal',
            name='total_donativos',
            field=models.CharField(max_length=50),
        ),
    ]
