# Generated by Django 4.2.3 on 2023-08-05 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donacion', '0008_rename_monto_a_recuadar_principal_monto_a_recaudar'),
    ]

    operations = [
        migrations.CreateModel(
            name='camapania',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_campania', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=500)),
                ('beneficiario', models.CharField(max_length=200)),
                ('monto_a_recaudar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_recaudado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_inicio', models.DateField()),
                ('fecha_cierre', models.DateField()),
                ('status', models.BooleanField()),
                ('imagen', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'campania',
            },
        ),
        migrations.CreateModel(
            name='categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'categorias_campañas',
            },
        ),
        migrations.CreateModel(
            name='donacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=500)),
                ('usuario', models.CharField(max_length=200)),
                ('valor_donado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_donativo', models.DateField()),
                ('comentario', models.CharField(max_length=500)),
                ('nombre_campania', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donacion.camapania')),
            ],
            options={
                'db_table': 'donacion',
            },
        ),
        migrations.RemoveField(
            model_name='educacion',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='humanitaria',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='salud',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='animal',
        ),
        migrations.DeleteModel(
            name='educacion',
        ),
        migrations.DeleteModel(
            name='humanitaria',
        ),
        migrations.DeleteModel(
            name='principal',
        ),
        migrations.DeleteModel(
            name='salud',
        ),
        migrations.AddField(
            model_name='camapania',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donacion.categorias'),
        ),
    ]
