# Generated by Django 4.2.3 on 2023-08-08 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donacion', '0010_rename_camapania_campania_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donacion',
            name='fecha_donativo',
        ),
        migrations.AlterField(
            model_name='campania',
            name='descripcion',
            field=models.CharField(max_length=5000),
        ),
    ]
