# Generated by Django 4.2.3 on 2023-08-08 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donacion', '0011_remove_donacion_fecha_donativo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donacion',
            name='fecha_donativo',
            field=models.DateField(null=True),
        ),
    ]
