# Generated by Django 4.2.3 on 2023-08-16 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donacion', '0012_donacion_fecha_donativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donacion',
            name='nombre_campania',
            field=models.CharField(max_length=200),
        ),
    ]
