# Generated by Django 4.2.3 on 2023-08-17 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donacion', '0014_alter_donacion_nombre_campania'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donacion',
            name='comentario',
            field=models.CharField(max_length=5000),
        ),
    ]
