# Generated by Django 4.2.3 on 2023-08-21 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donacion', '0015_alter_donacion_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donacion',
            name='nombre_campania',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donaciones', to='donacion.campania'),
        ),
    ]
