# Generated by Django 4.2.3 on 2023-08-26 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donacion', '0017_comentarios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentarios',
            old_name='name',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='comentarios',
            old_name='body',
            new_name='contenido',
        ),
    ]
