# Generated by Django 4.2.3 on 2023-08-26 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donacion', '0018_rename_name_comentarios_autor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentarios',
            old_name='contenido',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='comentarios',
            old_name='autor',
            new_name='name',
        ),
    ]
