# Generated by Django 4.2.3 on 2023-08-27 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donacion', '0019_rename_contenido_comentarios_body_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campania',
            options={'verbose_name_plural': 'campañas'},
        ),
        migrations.AlterModelOptions(
            name='categorias',
            options={'verbose_name_plural': 'categorias_campañas'},
        ),
        migrations.AlterModelOptions(
            name='donacion',
            options={'verbose_name_plural': 'donaciones'},
        ),
        migrations.AlterField(
            model_name='donacion',
            name='comentario',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterModelTable(
            name='campania',
            table='campaña',
        ),
        migrations.AlterModelTable(
            name='categorias',
            table='categoria_campaña',
        ),
        migrations.DeleteModel(
            name='Comentarios',
        ),
    ]
