# Generated by Django 4.2.3 on 2023-08-29 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donacion', '0020_alter_campania_options_alter_categorias_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campania',
            name='imagen',
            field=models.CharField(max_length=5000),
        ),
    ]
