# Generated by Django 4.2.3 on 2023-09-01 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donacion', '0022_solicitudes_campanias'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitudes_campanias',
            options={'verbose_name_plural': 'nuevas_solicitudes'},
        ),
        migrations.AlterModelTable(
            name='solicitudes_campanias',
            table='nueva_solicitud',
        ),
    ]
